version: '3'

services:
  geek-navigation:
    image: zjkl/geek-navigation
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2
    command: "mongod --profile=1 --slowms=1"
